// for store management
export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';

export const USER_DATA_REQUEST = 'USER_DATA_REQUEST';
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA_FAIL = 'USER_DATA_FAIL';

export const CONNECT_USER_FAIL = 'CONNECT_USER_FAIL';
export const CONNECT_USER_REQUEST = 'CONNECT_USER_REQUEST';
export const CONNECT_USER_SUCCESS = 'CONNECT_USER_SUCCESS';

export const DASHBOARD_INFO_REQUEST = 'DASHBOARD_INFO_REQUEST';
export const DASHBOARD_INFO_SUCCESS = 'DASHBOARD_INFO_SUCCESS';
export const DASHBOARD_INFO_FAIL = 'DASHBOARD_INFO_FAIL';

export const ALL_STAFF_REQUEST = 'ALL_STAFF_REQUEST';
export const ALL_STAFF_SUCCESS = 'ALL_STAFF_SUCCESS';
export const ALL_STAFF_FAIL = 'ALL_STAFF_FAIL';

export const ALL_STUDENTS_REQUEST = 'ALL_STUDENTS_REQUEST';
export const ALL_STUDENTS_SUCCESS = 'ALL_STUDENTS_SUCCESS';
export const ALL_STUDENTS_FAIL = 'ALL_STUDENTS_FAIL';

export const USER_DEVICES_REQUEST = 'USER_DEVICES_REQUEST';
export const USER_DEVICES_SUCCESS = 'USER_DEVICES_SUCCESS';
export const USER_DEVICES_FAIL = 'USER_DEVICES_FAIL';

export const ADD_STAFF_DUTY_FAIL = 'ADD_STAFF_DUTY_FAIL';
export const ADD_STAFF_DUTY_REQUEST = 'ADD_STAFF_DUTY_REQUEST';
export const DELETE_STAFF_DUTY_REQUEST = 'DELETE_STAFF_DUTY_REQUEST';
export const ADD_STAFF_DUTY_SUCCESS = 'ADD_STAFF_DUTY_SUCCESS';
export const DELETE_STAFF_DUTY_SUCCESS = 'DELETE_STAFF_DUTY_SUCCESS';
export const DELETE_STAFF_DUTY_FAIL = 'DELETE_STAFF_DUTY_FAIL';
export const ADD_STAFF_DUTY_RESET = 'ADD_STAFF_DUTY_RESET';
export const DELETE_STAFF_DUTY_RESET = 'DELETE_STAFF_DUTY_RESET';

export const ADD_ROUTINE_REQUEST = 'ADD_ROUTINE_REQUEST';
export const DELETE_ROUTINE_REQUEST = 'DELETE_ROUTINE_REQUEST';
export const ADD_ROUTINE_SUCCESS = 'ADD_ROUTINE_SUCCESS';
export const DELETE_ROUTINE_SUCCESS = 'DELETE_ROUTINE_SUCCESS';
export const ADD_ROUTINE_FAIL = 'ADD_ROUTINE_FAIL';
export const DELETE_ROUTINE_FAIL = 'DELETE_ROUTINE_FAIL';
export const ADD_ROUTINE_RESET = 'ADD_ROUTINE_RESET';
export const DELETE_ROUTINE_RESET = 'DELETE_ROUTINE_RESET';

export const DOWNLOAD_PDF_REQUEST = 'DOWNLOAD_PDF_REQUEST';
export const DOWNLOAD_PDF_SUCCESS = 'DOWNLOAD_PDF_SUCCESS';
export const DOWNLOAD_PDF_FAILURE = 'DOWNLOAD_PDF_FAILURE';
export const DOWNLOAD_PDF_RESET = 'DOWNLOAD_PDF_RESET';

export const ZK_TECO_ATTENDANCE_REQUEST = 'ZK_TECO_ATTENDANCE_REQUEST';
export const ZK_TECO_ATTENDANCE_SUCCESS = 'ZK_TECO_ATTENDANCE_SUCCESS';
export const ZK_TECO_ATTENDANCE_FAIL = 'ZK_TECO_ATTENDANCE_FAIL';

export const ALL_OFFICIANT_ATTENDANCE_REQUEST =
  'ALL_OFFICIANT_ATTENDANCE_REQUEST';
export const ALL_OFFICIANT_ATTENDANCE_SUCCESS =
  'ALL_OFFICIANT_ATTENDANCE_SUCCESS';
export const ALL_OFFICIANT_ATTENDANCE_FAIL = 'ALL_OFFICIANT_ATTENDANCE_FAIL';
export const ALL_OFFICIANT_ATTENDANCE_RESET = 'ALL_OFFICIANT_ATTENDANCE_RESET';

export const ALL_STUDENT_ATTENDANCE_REQUEST = 'ALL_STUDENT_ATTENDANCE_REQUEST';
export const ALL_STUDENT_ATTENDANCE_SUCCESS = 'ALL_STUDENT_ATTENDANCE_SUCCESS';
export const ALL_STUDENT_ATTENDANCE_RESET = 'ALL_STUDENT_ATTENDANCE_RESET';
export const ALL_STUDENT_ATTENDANCE_FAIL = 'ALL_STUDENT_ATTENDANCE_FAIL';

export const ZK_TECO_LIVE_REQUEST = 'ZK_TECO_LIVE_REQUEST';
export const ZK_TECO_LIVE_SUCCESS = 'ZK_TECO_LIVE_SUCCESS';
export const ZK_TECO_LIVE_FAIL = 'ZK_TECO_LIVE_FAIL';

export const DELETE_OFFICIANT_ATTENDANCE_REQUEST =
  'DELETE_OFFICIANT_ATTENDANCE_REQUEST';
export const DELETE_OFFICIANT_ATTENDANCE_SUCCESS =
  'DELETE_OFFICIANT_ATTENDANCE_SUCCESS';
export const DELETE_OFFICIANT_ATTENDANCE_FAIL =
  'DELETE_OFFICIANT_ATTENDANCE_FAIL';
export const DELETE_OFFICIANT_ATTENDANCE_RESET =
  'DELETE_OFFICIANT_ATTENDANCE_RESET';

export const DELETE_STUDENT_ATTENDANCE_REQUEST =
  'DELETE_STUDENT_ATTENDANCE_REQUEST';
export const DELETE_STUDENT_ATTENDANCE_SUCCESS =
  'DELETE_STUDENT_ATTENDANCE_SUCCESS';
export const DELETE_STUDENT_ATTENDANCE_FAIL = 'DELETE_STUDENT_ATTENDANCE_FAIL';
export const DELETE_STUDENT_ATTENDANCE_RESET =
  'DELETE_STUDENT_ATTENDANCE_RESET';

export const SETTINGS_REQUEST = 'SETTINGS_REQUEST';
export const SETTINGS_SUCCESS = 'SETTINGS_SUCCESS';
export const SETTINGS_FAIL = 'SETTINGS_FAIL';

export const SEND_SMS_REQUEST = 'SEND_SMS_REQUEST';
export const SEND_SMS_SUCCESS = 'SEND_SMS_SUCCESS';
export const SEND_SMS_FAIL = 'SEND_SMS_FAIL';

export const ZK_TECO_SAVE_RESET = 'ZK_TECO_SAVE_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const getZktecoUserTypes = (t) => [
  { value: 'admin', label: t('admin') },
  { value: 'general', label: t('general') },
];

export const getAttendanceTypes = (t) => [
  { value: '', label: t('select') },
  { value: 'card', label: t('idCard') },
  { value: 'finger', label: t('fingerPrint') },
  { value: 'pin', label: t('pinCode') },
  { value: 'all', label: `${t('idCard')}/${t('fingerPrint')}/${t('pinCode')}` },
];

export const BASE_URL_EXPRESS = 'http://localhost:4010';
export const BASE_URL_FLASK = 'http://localhost:4011';
