export const ZK_TECO_CONNECTION_REQUEST = 'ZK_TECO_CONNECTION_REQUEST';
export const ZK_TECO_CONNECTION_SUCCESS = 'ZK_TECO_CONNECTION_SUCCESS';
export const ZK_TECO_CONNECTION_FAIL = 'ZK_TECO_CONNECTION_FAIL';
export const ZK_TECO_CONNECTION_RESET = 'ZK_TECO_CONNECTION_RESET';

export const ZK_TECO_NEW_USER_REQUEST = 'ZK_TECO_NEW_USER_REQUEST';
export const ZK_TECO_NEW_USER_SUCCESS = 'ZK_TECO_NEW_USER_SUCCESS';
export const ZK_TECO_NEW_USER_FAIL = 'ZK_TECO_NEW_USER_FAIL';
export const ZK_TECO_NEW_USER_RESET = 'ZK_TECO_NEW_USER_RESET';

export const ZK_TECO_LOGS_REQUEST = 'ZK_TECO_LOGS_REQUEST';
export const ZK_TECO_LOGS_SUCCESS = 'ZK_TECO_LOGS_SUCCESS';
export const ZK_TECO_LOGS_FAIL = 'ZK_TECO_LOGS_FAIL';
export const ZK_TECO_LOGS_RESET = 'ZK_TECO_LOGS_RESET';
export const CLEAR_LOGS = 'CLEAR_LOGS';

export const ZK_TECO_USERS_REQUEST = 'ZK_TECO_USERS_REQUEST';
export const ZK_TECO_USERS_SUCCESS = 'ZK_TECO_USERS_SUCCESS';
export const ZK_TECO_USERS_FAIL = 'ZK_TECO_USERS_FAIL';

export const ZK_TECO_DELETE_USER_REQUEST = 'ZK_TECO_DELETE_USER_REQUEST';
export const ZK_TECO_DELETE_USER_SUCCESS = 'ZK_TECO_DELETE_USER_SUCCESS';
export const ZK_TECO_DELETE_USER_FAIL = 'ZK_TECO_DELETE_USER_FAIL';
export const ZK_TECO_DELETE_USER_RESET = 'ZK_TECO_DELETE_USER_RESET';

export const ZK_TECO_DEVICE_DELETE_REQUEST = 'ZK_TECO_DEVICE_DELETE_REQUEST';
export const ZK_TECO_DEVICE_DELETE_SUCCESS = 'ZK_TECO_DEVICE_DELETE_SUCCESS';
export const ZK_TECO_DEVICE_DELETE_FAIL = 'ZK_TECO_DEVICE_DELETE_FAIL';
export const ZK_TECO_DEVICE_DELETE_RESET = 'ZK_TECO_DEVICE_DELETE_RESET';

export const ZK_TECO_ATTENDANCE_REQUEST = 'ZK_TECO_ATTENDANCE_REQUEST';
export const ZK_TECO_ATTENDANCE_SUCCESS = 'ZK_TECO_ATTENDANCE_SUCCESS';
export const ZK_TECO_ATTENDANCE_FAIL = 'ZK_TECO_ATTENDANCE_FAIL';
export const ZK_TECO_ATTENDANCE_RESET = 'ZK_TECO_ATTENDANCE_RESET';

export const ZK_TECO_DELETE_ATTENDANCE_REQUEST =
  'ZK_TECO_DELETE_ATTENDANCE_REQUEST';
export const ZK_TECO_DELETE_ATTENDANCE_SUCCESS =
  'ZK_TECO_DELETE_ATTENDANCE_SUCCESS';
export const ZK_TECO_DELETE_ATTENDANCE_FAIL = 'ZK_TECO_DELETE_ATTENDANCE_FAIL';
export const ZK_TECO_DELETE_ATTENDANCE_RESET =
  'ZK_TECO_DELETE_ATTENDANCE_RESET';

export const ZK_TECO_DEVICES_REQUEST = 'ZK_TECO_DEVICES_REQUEST';
export const ZK_TECO_DEVICES_SUCCESS = 'ZK_TECO_DEVICES_SUCCESS';
export const ZK_TECO_DEVICES_FAIL = 'ZK_TECO_DEVICES_FAIL';

export const ZK_TECO_LIVE_REQUEST = 'ZK_TECO_LIVE_REQUEST';
export const ZK_TECO_LIVE_SUCCESS = 'ZK_TECO_LIVE_SUCCESS';
export const ZK_TECO_LIVE_FAIL = 'ZK_TECO_LIVE_FAIL';
export const ZK_TECO_LIVE_RESET = 'ZK_TECO_LIVE_RESET';

export const ZK_TECO_SAVE_REQUEST = 'ZK_TECO_SAVE_REQUEST';
export const ZK_TECO_SAVE_SUCCESS = 'ZK_TECO_SAVE_SUCCESS';
export const ZK_TECO_SAVE_FAIL = 'ZK_TECO_SAVE_FAIL';
export const ZK_TECO_SAVE_RESET = 'ZK_TECO_SAVE_RESET';

export const ZK_TECO_CLOSE_LIVE_REQUEST = 'ZK_TECO_CLOSE_LIVE_REQUEST';
export const ZK_TECO_CLOSE_LIVE_SUCCESS = 'ZK_TECO_CLOSE_LIVE_SUCCESS';
export const ZK_TECO_CLOSE_LIVE_FAIL = 'ZK_TECO_CLOSE_LIVE_FAIL';

export const INSERT_REQUEST = 'INSERT_REQUEST';
export const INSERT_SUCCESS = 'INSERT_SUCCESS';
export const INSERT_FAIL = 'INSERT_FAIL';

export const GET_REQUEST = 'GET_REQUEST';
export const GET_SUCCESS = 'GET_SUCCESS';
export const GET_FAIL = 'GET_FAIL';
export const GET_RESET = 'GET_RESET';

export const GET_RULS_FAIL = 'GET_RULS_FAIL';
export const GET_RULS_REQUEST = 'GET_RULS_REQUEST';
export const GET_RULS_SUCCESS = 'GET_RULS_SUCCESS';

export const PUSH_REQUEST = 'PUSH_REQUEST';
export const PUSH_SUCCESS = 'PUSH_SUCCESS';
export const PUSH_FAIL = 'PUSH_FAIL';
export const PUSH_RESET = 'PUSH_RESET';

export const GET_DEVICE_CAPACITY_REQUEST = 'GET_DEVICE_CAPACITY_REQUEST';
export const GET_DEVICE_CAPACITY_SUCCESS = 'GET_DEVICE_CAPACITY_SUCCESS';
export const GET_DEVICE_CAPACITY_FAIL = 'GET_DEVICE_CAPACITY_FAIL';

export const getDeviceUsers = (t) => [
  { label: t('student'), value: 'Student' },
  { label: t('officiant'), value: 'Officiant' },
  { label: `${t('student')}/${t('officiant')}`, value: 'All' },
];

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
